// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/controls/ControlsA.tsx": () => import("../components/mockups/controls/ControlsA.tsx"),
  "./components/mockups/controls/ControlsB.tsx": () => import("../components/mockups/controls/ControlsB.tsx"),
  "./components/mockups/controls/ControlsC.tsx": () => import("../components/mockups/controls/ControlsC.tsx")
};
